name: Sandbox

on:
  push:
    branches-ignore:
      - 'master'
  workflow_dispatch:

jobs:  
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy-common.yml
    with:
      NODE_ENV: 'debug'
      deploy: ${{ github.ref_name == 'develop' && !contains(github.event.head_commit.message, '--skip-deploy') }}
      tests: ${{ !contains(github.event.head_commit.message, '--skip-tests') }}
      migrations: ${{ !contains(github.event.head_commit.message, '--skip-migrations') }}
      server: ${{ !contains(github.event.head_commit.message, '--skip-server') }}
      studio: ${{ !contains(github.event.head_commit.message, '--skip-studio') }}
      STUDIO_URL: 'INIT__SANDBOX_STUDIO_URL'
      SERVER_URL: 'INIT__SANDBOX_SERVER_URL'
    secrets:
      publishProfile: ${{ secrets.INIT__GITHUB_SECRET_SANDBOX_PUBLIC_PROFILE }}
      STATIC_WEB_APPS_TOKEN: ${{ secrets.INIT__GITHUB_SECRET_SANDBOX_STATIC_WEB_APPS_TOKEN }}
      DATABASE_USERNAME: ${{ secrets.INIT__GITHUB_SECRET_SANDBOX_DATABASE_USERNAME }}
      DATABASE_PASSWORD: ${{ secrets.INIT__GITHUB_SECRET_SANDBOX_DATABASE_PASSWORD }}
      DATABASE_HOST: ${{ secrets.INIT__GITHUB_SECRET_SANDBOX_DATABASE_HOST }}
      DATABASE_PORT: ${{ secrets.INIT__GITHUB_SECRET_SANDBOX_DATABASE_PORT }}
